name: Time-Based Trending Posts

on:
  schedule:
    # Every 2 hours (00:00, 02:00, 04:00, ... 22:00)
    - cron: '0 */2 * * *'
  workflow_dispatch:
    inputs:
      num_images:
        description: 'Number of images in reel'
        required: false
        default: '5'
      duration:
        description: 'Total video duration in seconds (10–90)'
        required: false
        default: '10'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          pip install google-generativeai requests pillow
          pip install --upgrade google-auth google-auth-httplib2 google-api-python-client httplib2

      - name: Download and install ffmpeg
        run: |
          mkdir -p $HOME/bin
          curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
          tar -xf ffmpeg.tar.xz
          mv ffmpeg-*-amd64-static/ffmpeg $HOME/bin/
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Select Niche Based on Time (Global Trend Rotation)
        id: time-niche
        run: |
          # 🌍 Full 10-day (120-slot) global trending niche rotation
          NICHES=(
            # Day 1
            "AI Bollywood Portraits (India)"
            "Festive Street Food Vlogs (India)"
            "Diwali Home Decor Tips (India)"
            "Budget Travel within 200km (India)"
            "Morning Fitness Challenge (India)"
            "Motivational Quotes + Music (India)"
            "Marathi Village Food Stories (India)"
            "AI Saree Design Showcase (India)"
            "Work From Cafe Reels (India)"
            "Minimal Home Setup Aesthetic (India)"
            "Local Language Shorts Marathi/Hindi (India)"
            "Diwali Outfit Inspiration (India)"
            # Day 2
            "Bangkok Street Food Crawl (Thailand)"
            "K-Beauty Skincare Routine (Korea)"
            "Tokyo Autumn Aesthetic (Japan)"
            "Solo Travel in Bali (Indonesia)"
            "AI Pet Portraits (Asia)"
            "Morning Coffee Vibes (Global)"
            "London Streetwear Fall Looks (UK)"
            "Paris Cafe Culture Reels (France)"
            "Dubai Luxury Cars & Lifestyle (UAE)"
            "Sustainable Fashion Haul (Europe)"
            "AI Music Remix Trend (Global)"
            "Travel Drone Shorts (Turkey)"
            # Day 3
            "Pumpkin Spice Season Recipes (US)"
            "Halloween Costume DIY (US)"
            "NYC Street Interviews (US)"
            "Tech Productivity Apps (US)"
            "Workout Meal Prep (US)"
            "Home Office Aesthetic (US)"
            "Cozy Fall Recipes (US)"
            "Morning Affirmations (US)"
            "Street Basketball Vibes (US)"
            "Night Sky Timelapse (Global)"
            "Motivation After 10pm (Global)"
            "Crypto AI Startup Insights (Global)"
            # Day 4
            "Trending TikTok Sounds Remix (Global)"
            "Minimalist Travel Gear (Global)"
            "Unboxing Gadgets (Global)"
            "Couple Challenge Trend (Global)"
            "Mini Vlog Aesthetic (Global)"
            "Before/After Transformations (Global)"
            "30-Day Fitness Transformation (Global)"
            "Street Style Fits (Global)"
            "AI Art Mashups (Global)"
            "Diwali Lighting Hacks (India)"
            "Ganpati Decoration DIY (India)"
            "Indian Snacks Fusion Recipe (India)"
            # Day 5
            "AI Actor Look Generator (India)"
            "Local Train Aesthetic Reels (India)"
            "Mumbai Monsoon Throwback (India)"
            "Cafe Review Mini Vlog (India)"
            "Quick Office Lunch Recipes (India)"
            "Hindi Motivational Shorts (India)"
            "Travel with Parents Series (India)"
            "Self-Care Sunday Routine (India)"
            "Pet Reels Compilation (India)"
            "Goa Weekend Getaway (India)"
            "Fashion Dupes on Budget (India)"
            "Viral Meme Format Reels (India)"
            # Day 6
            "Morning Mindset Boost (Asia)"
            "Minimal Tech Desk Setup (Asia)"
            "Productivity Hack of the Day (Asia)"
            "Best Camera Apps 2025 (Asia)"
            "AI Storytelling Reels (Asia)"
            "Korean Street Dance (Korea)"
            "Tokyo Neon Nights (Japan)"
            "Singapore Food Market (Asia)"
            "Bali Beach Chill Reel (Asia)"
            "Luxury Hotel Tour (Asia)"
            "Street Food Taste Test (Asia)"
            "AI Mascot Creation Trend (Asia)"
            # Day 7
            "European Autumn Fashion Lookbook (EU)"
            "Paris Sunset Timelapse (France)"
            "Berlin Startup Life (Germany)"
            "Italian Coffee Routine (Italy)"
            "Sustainable Living Hacks (EU)"
            "London City Walk POV (UK)"
            "Copenhagen Interior Design (Denmark)"
            "Vintage Thrift Reels (EU)"
            "Street Performance Clips (EU)"
            "Local Artist Feature (EU)"
            "AI-Generated Music Loops (EU)"
            "Festival Highlights (EU)"
            # Day 8
            "Fall Fitness Challenge (US)"
            "Motivation Monday Reels (US)"
            "Tech News Recap (US)"
            "Behind the Scenes Mini Vlog (US)"
            "Home Decor DIY Hacks (US)"
            "College Life Day in the Life (US)"
            "Pet Care Tips (US)"
            "AI Meme Generator Trend (US)"
            "Morning Smoothie Recipes (US)"
            "Weekend Productivity Routine (US)"
            "Funny Couple Reels (US)"
            "New Viral Transition Effect (US)"
            # Day 9
            "Drone Reel of the Week (Global)"
            "Street Culture Edits (Global)"
            "Gaming Highlight Shorts (Global)"
            "AI Voice-Over Narration (Global)"
            "Digital Nomad Lifestyle (Global)"
            "Motivational Sound Mashups (Global)"
            "Cinematic Travel Transitions (Global)"
            "One-Minute Tutorials (Global)"
            "Visual Illusion Reels (Global)"
            "Street Dance Collaboration (Global)"
            "Best Free AI Tools 2025 (Global)"
            "Time-Lapse City Life (Global)"
            # Day 10
            "Mindfulness Routine (Global)"
            "ASMR Coffee Pour (Global)"
            "Slow-Mo Transformation (Global)"
            "Morning Beach Meditation (Global)"
            "AI Cartoonify Yourself (Global)"
            "Color Grading Reels (Global)"
            "Nature Sound Compilation (Global)"
            "Positive Affirmation Shorts (Global)"
            "Workspace Setup Tours (Global)"
            "Recreate Old Photo Challenge (Global)"
            "Trending Reel Sound Sync (Global)"
            "Weekly Highlight Montage (Global)"
          )

          # Calculate index by time (every 2 hours = 7200 sec)
          INDEX=$(( ( ( $(date +%s) / 7200 ) % ${#NICHES[@]} ) ))
          SELECTED_NICHE=${NICHES[$INDEX]}
          echo "🎯 Auto-selected niche: $SELECTED_NICHE"
          echo "niche=$SELECTED_NICHE" >> $GITHUB_OUTPUT

      - name: Generate and Post Reel
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_UPLOAD_PRESET: ${{ secrets.CLOUDINARY_UPLOAD_PRESET }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          CLIENT_ID_YOUTUBE: ${{ secrets.CLIENT_ID_YOUTUBE }}
          CLIENT_SECRET_YOUTUBE: ${{ secrets.CLIENT_SECRET_YOUTUBE }}
          REFRESH_TOKEN_YOUTUBE: ${{ secrets.REFRESH_TOKEN_YOUTUBE }}

          # Same logic for both schedule & manual trigger
          REEL_NICHE: ${{ steps.time-niche.outputs.niche }}
          REEL_IMAGES: ${{ github.event.inputs.num_images || '5' }}
          REEL_DURATION: ${{ github.event.inputs.duration || '10' }}
        run: |
          echo "🎥 Posting Reel for niche: $REEL_NICHE"
          echo "🖼️  Using $REEL_IMAGES images, Duration: $REEL_DURATION sec"
          python -u insta_reels_new.py

      - name: Success
        if: success()
        run: echo "✅ Reel posted successfully!"

      - name: Failure
        if: failure()
        run: echo "❌ Failed to post reel"
